name: build
on:
  push:
  schedule:
    - cron: "0 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: humble
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install rust
        run: |
          apt install curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustc --version
          cargo --version
      - name: Install gazebo
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update -qq
          apt install -qq -y lsb-release wget curl gnupg2 python3-kconfiglib python3-jinja2 python3-jsonschema ros-humble-gps-msgs gcc-arm-none-eabi libfuse2 python3-pip python3-future rsync python3-genmsg
          wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
          apt-get update && apt-get install -qq -y gz-garden
      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name:
          vcs-repo-file-url: |
            $GITHUB_WORKSPACE/dependencies.repos
          target-ros2-distro: humble
          rosdep-skip-keys: gz-transport12 gz-common5 gz-math7 gz-msgs9 gz-gui7 gz-cmake3 gz-sim7
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DSKIP_QGROUNDCONTROL=1"
                ],
                "hooks": [
                  "$HOME/.cargo/env",
                ]
              },
              "test": {
                "retest-until-pass": 5
              },
              "test": {
                "packages-select-regex": [
                  "vehicle_gateway"
                ]
              }
            }
